package com.atletry.enums;

public enum VenueType {
    SINGLE_COURT_SINGLE_SPORT,
    MULTIPLE_COURTS_SAME_SPORT,
    BOX_CRICKET_FACILITY,
    FOOTBALL_MULTI_SPORT_TURF,
    MULTI_SPORT_FACILITY,
    SPORTS_COMPLEX,
    SWIMMING_POOL,
    SOMETHING_ELSE
}
